name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_design_system:
    path: ../
  web: ^1.1.1
  widgetbook: ^3.13.1
  widgetbook_annotation: ^3.3.0
  country_code_picker: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  widgetbook_generator: ^3.10.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
